name: f_cleaner
description: A CLI tool to scan directories for Flutter projects and run 'flutter clean' to free up disk space.
version: 1.0.0

homepage: https://github.com/Jamalianpour/f_cleaner

environment:
  sdk: ^3.6.0

dependencies:
  path: ^1.9.1
  args: ^2.6.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0

executables:
  f_cleaner: f_cleaner